---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: blog
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/Rolyani/blog-final
  ref:
    branch: main
  secretRef:
    name: blog-git-auth
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: blog-db-migrate
  namespace: flux-system
spec:
  interval: 10m
  path: ./infrastructure/k8s/base/migrate-job
  prune: true
  wait: true
  timeout: 5m
  force: true
  targetNamespace: blog
  sourceRef:
    kind: GitRepository
    name: blog
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: blog-staging
  namespace: flux-system
spec:
  interval: 10m
  path: ./infrastructure/k8s/staging
  prune: true
  wait: true
  timeout: 10m
  targetNamespace: blog
  sourceRef:
    kind: GitRepository
    name: blog
  dependsOn:
    - name: blog-db-migrate
  decryption:
    provider: sops
    secretRef:
      name: sops-age
