apiVersion: v1
kind: Secret
metadata:
    name: blog-git-auth
    namespace: flux-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:6mZOHmn0aQ==,iv:A+zZ1TrUKup7SLV1wlh16/YcGWIIKH1HLrpsuyVx6/E=,tag:QXOTleMvZzBLf4a5MDHU0A==,type:str]
    password: ENC[AES256_GCM,data:ZGIc/NuCk9shzpkOce/xObUv82RXn9EiM3p7JOTO8qDac+duat6LrfJhMvFHTWbeQcU8yYrq7PqIENusw4Jkdwpj/93b1LWQW+Dzq2/ByHxD080YvNzyCO9brIR6,iv:EqsiEglxBMmcIb1jpgbwbmeK80BoNxnvxMLbtc7IyCA=,tag:/TSFYzdUV86RZKP4lY058w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tknk79czu7utxqpkampa72mxdmh0atwfjsqeda9egwu2xfvn8qaqr43j44
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJdS96amhtN1h2dDhZM3Yv
            NG5lTDgzcnpxRGRzaGRRZlRXU01EMmdxSzBFClFZWUN2RGtvTDRlNmh6bjFlWGFD
            VXVXNVVYa3pIS0ZESXlSdHBDU0lYY1UKLS0tIDRCTFJ5U3lnc0laSFMrRE9Fck5J
            ZUw5ck1LQ1JOSUZsN0x2b0RPcUZ1ZDAKNV6MYcPLTOFt7NQd9gNQ86hdJdbfiLrw
            XVp3OYbPG0K7vuyGhC01kH9YJG4xHabLhDWiO0Q2LZn34e4MxFk0CA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-26T10:57:19Z"
    mac: ENC[AES256_GCM,data:oqTHOfqyuiHs/FlnAV2PDpdgkiUR4jydQ9dapJPwdfjLVi0ru8tPtFwoVqeAXJWDQHCOTuvxnW+HiOCmElFkQ8/BLTb3S/nlD/Z702jgQG/c3bW+T3TM/A0aQjijsm7JTIXcR7ah6kEGevX1x9H8iY+GfT4vlNHfEU14JRusCA8=,iv:LiOq37akD9+m+Cbds8QRsgb9bCyd9P36Zi3+uqVAv68=,tag:zGPHzzOrbBeYt4GSb+FMWw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
