apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
  - infrastructure-controllers-kustomization.yaml
  - longhorn-kustomization.yaml
  - apps-kustomization.yaml
  - monitoring-kustomization.yaml
  # - blog-git-auth-secret.yaml      # uncomment in Commit B
  # - blog-kustomization.yaml         # uncomment in Commit B
patches:
  - target:
      group: kustomize.toolkit.fluxcd.io
      kind: Kustomization
      name: flux-system
      namespace: flux-system
    patch: |
      - op: add
        path: /spec/decryption
        value:
          provider: sops
          secretRef:
            name: sops-age
