apiVersion: v1
kind: Secret
metadata:
    name: mp-telegram-bot-token
    namespace: mp-telegram-bot
type: Opaque
stringData:
    TELEGRAM_TOKEN: ENC[AES256_GCM,data:kGk0054rXxg0DAsb52F07bMXDHJytpckmQN+9nHo+OQL8WAJ61+5C56LObhK2g==,iv:Gw3CuVPcBKSCBNR1okAexr1lbtL43mRwME75cFo4HW0=,tag:+qpNKuODdYYy3uzLd6i35w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tknk79czu7utxqpkampa72mxdmh0atwfjsqeda9egwu2xfvn8qaqr43j44
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLY0Y4ZXQ4WXl5SkRUbXNR
            NS9vUGloOGNPT3NMMDJsaTVkR3AvT0JCQVJzCnBWZlQ2QTFHNkJncEdHMGlqajNh
            dmxDdEMzNjNVaTVjM0ZOeGJlUXBkdDAKLS0tIHB4Q2N5ZnNtL2tDcStaTlA5RmxX
            YlVjNWZlUThEWTNuN0hUZVNwOFB5b1kKFBgg/R94zpygvtgpcDnetVl5oL5Bpyy0
            I6N0D4xaRewEf5uQJ2xq66rWqjMiMM5Bvmd3Uya/H4MDy4hU1+L1RQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-23T19:55:29Z"
    mac: ENC[AES256_GCM,data:k01wOKYJ+QklaBPBfoM6F06tkmH9apL/Mc4DTedldK1SiyupZZoBE79E/3YILPgP4uFsjDdxlAxdBHUCqzpAEYLFAPRzeAOY75dQqyR4yTVXXN//RdSY6BDnGdnx4SvjKFzETSUVA+XR1A6kKKpZVfhGCioqkt8s3YmVz9GRSJc=,iv:XxnqwYEERPaVnyEwawJ8F07SY0OP/vKz2TzZGDknxP0=,tag:bxcU9sRhBhoso3JZArMg8Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
