apiVersion: apps.kubeblocks.io/v1alpha1
kind: Cluster
metadata:
  name: blog-mysql
  namespace: lessons-in-progress
spec:
  terminationPolicy: Delete
  componentSpecs:
    - name: mysql
      componentDefRef: mysql
      version: mysql-8.0.33
      replicas: 1
      volumeClaimTemplates:
        - name: data
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 10Gi

