apiVersion: apps.kubeblocks.io/v1alpha1
kind: Cluster
metadata:
  name: blog-mysql
  namespace: lessons-in-progress
spec:
  clusterDefinitionRef: mysql
  clusterVersionRef: mysql-8.0.33
  terminationPolicy: Delete
  componentSpecs:
    - name: mysql
      componentDefRef: mysql
      replicas: 1
      volumeClaimTemplates:
        - name: data
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 10Gi
