apiVersion: batch/v1
kind: Job
metadata:
  name: posts-migration
  namespace: lessons-in-progress
spec:
  backoffLimit: 1
  template:
    spec:
      containers:
        - name: migrate
          image: ianrn/microservice-blog-posts-service:v1.0.0
          command: ["php", "artisan", "migrate", "--force"]
          envFrom:
            - secretRef:
                name: blog-db-secret
      restartPolicy: Never

