apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dashy
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: dashy
      version: 1.0.0
      sourceRef:
        kind: HelmRepository
        name: dashy
        namespace: flux-system
  targetNamespace: dashy
  valuesFrom:
    - kind: ConfigMap
      name: configmap
      valuesKey: conf.yaml
      namespace: dashy
  values:
    service:
      type: ClusterIP
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: web
      hosts:
        - host: dash.ian-naylor.com
          paths:
            - path: /
              pathType: Prefix

