apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealie
  namespace: mealie
  labels:
    app: mealie
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mealie
  template:
    metadata:
      labels:
        app: mealie
    spec:
      containers:
        - name: mealie
          image: ghcr.io/mealie-recipes/mealie:v3.19.2
          ports:
            - containerPort: 9000
          env:
            - name: ALLOW_SIGNUP
              value: "false"
            - name: TZ
              value: "Europe/London"
            - name: BASE_URL
              value: "https://mealie.ian-naylor.com"
            - name: DB_ENGINE
              value: "postgres"
            - name: POSTGRES_SERVER
              value: "mealie-db-rw"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: "mealie"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: mealie-db-app
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mealie-db-app
                  key: password
          volumeMounts:
            - name: data
              mountPath: /app/data
          livenessProbe:
            httpGet:
              path: /api/app/about
              port: 9000
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /api/app/about
              port: 9000
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mealie-data
