apiVersion: v1
kind: Secret
metadata:
    name: tunnel-credentials
    namespace: mealie
type: Opaque
stringData:
    credentials.json: ENC[AES256_GCM,data:/NFaT3L6HT959ufE8GhZX6Cbzw0SKfPBoZtf5o5rdoMHXZRG6YoIHqjQwaPfoxvVCVt1oQe3SLIkb3YtpaslAaS6ON733lsOdhJ9dzZCRkAt4EUY3/BFaLDWZufZyqt/hceMmz60p9v0CZU6KoqfqF0fGsJl8svIUxMhRKnYDPxidUusBQVq42n3VhKVbxJFC0aYiAtW+hi+X6RyJXanwdXtamPBGmsmXqNH9BkYuQ==,iv:XhFJcm0530X4lQ4lLED//gs0jyrkfKXlRP1yPANwnug=,tag:vFzjUxyOVXUphvfNieFPnQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tknk79czu7utxqpkampa72mxdmh0atwfjsqeda9egwu2xfvn8qaqr43j44
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvRUc1MjU4TWZvTmNCQzhE
            V3VyMXovY3hJQThIL2VMeTl6dU4vK203V2dFCk1PaHQvbDVvOUpJUWUvV3FQWEV6
            bmExL1pqeGxZaXFoSXVxbEVCSitBTzQKLS0tIGNNUXIzVUlkUXRZSjdUcE9jWjVr
            UzJkTjNjZmFHTFpRNGFQRHZGZ1M1UVUK42rlXGLYtrUc/Z4WtL5gnNhST2bJx88u
            Dl7y2KlWxbVioZY/bkqq5K08Fbat27fXHRhYF15sQH5IPXqY1DrZkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-13T13:34:52Z"
    mac: ENC[AES256_GCM,data:D6JFZFiSK5Q426hDEB6eS7MOYpq5b4YXFQSSKTDdfhtue4qzQTiITSsjlzv6PQqrgeyooCv1vQBMsVasaeRsjQP1uaCzLttMhO8/09bIAvyNjqxVTaNKB1UZSlU9vnHfjO1/UMmgnQbz9syw2zmKU0GlebdnUI0cLrBi8XnVGjc=,iv:EbrJ+oKHDbT5auRmRAsxQFco/tQCKZfv82ruSbl7hQ4=,tag:qT7jHnFQwKUqe33NNql6Vg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
