apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pull
    namespace: blog
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:394rbJkWSEiD352gbHPQ1t68ORtAqCpiLAeI8DdImmw6fYrt0suCOEeAYpbCiwNFOZFnqX8pItP1oRhDWLw28x/Xt88QckLDPUrI6HqrPqQ4+yoQHkx6D8VdtfAhv8qmxKmGPN5FX9nL+BJW1bQ2jdsblt3HyAO/TTbdyEWuL32i8S2TDt1JCnd6AE/TEcsaJlUwkFUuQEe8jKIv1SU9hymzlqQxJhqCMmvBbUA=,iv:adp2w2YP/4Si3xeZ5GQ6FKlK9sHaSvYdZVce6I3fYjc=,tag:JX0sQh96D2xVtsHgTGBtTA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tknk79czu7utxqpkampa72mxdmh0atwfjsqeda9egwu2xfvn8qaqr43j44
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQZzBidzZlVDQwN3E0ZlZC
            Tno0RlZiRHdJVXhkSVExYVp1NXpLNEQ2L0F3CkVzSTNweEJCWmliaUI0cTZEY2Zm
            OXBDbytmM3dHQ2R2NTVpYndDMG1ReXcKLS0tIDNYamFrdnlrMElDMEN0OHdOUTZP
            Z0E3WkNQZTZGK1RGZTZsSSs3bjVSbm8K+Kdo01o4pQqlyJcsTb/hyxOyoQcmSwts
            vNUnyYzu5ceroUJO9kYbYKQKGTIncUNC9hD9aGoMzVNb1ZoWasuc5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-26T11:43:42Z"
    mac: ENC[AES256_GCM,data:HyrCOE6aQ4pwuGnLk5dfREPftwLMuV6JHgdccz/CAmW8jdAwVUnYCg4Yt+JoHk/p3/jj8FXCJcQgm8tRZjb/0NqqY3o5AlGpEdJTNs8UtVG+HvPo+W7Jv84fCC377OxLNts9DzAXQcocOJW5iWnTD5/SX/yVBfLcQs7AABxpPBk=,iv:2a0b5m0ko90E74VAQSd4hz204VSBZeZy47zLIBAFo/0=,tag:Oy8MtMh2JGvXbal8LI0tng==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
