apiVersion: apps.kubeblocks.io/v1
kind: Cluster
metadata:
  name: lessons-mysql
  namespace: lessons-in-progress
spec:
  terminationPolicy: Delete
  clusterDef: mysql
  topology: semisync

  componentSpecs:
    - name: mysql
      replicas: 1
      serviceVersion: "8.0.44"
      volumeClaimTemplates:
        - name: data
          spec:
            storageClassName: longhorn
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 20Gi
