apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubeblocks
  namespace: kubeblocks
spec:
  interval: 10m
  chart:
    spec:
      chart: kubeblocks
      sourceRef:
        kind: HelmRepository
        name: kubeblocks
        namespace: kubeblocks
      version: "1.0.1"
  values:
    installCRDs: true
    autoInstalledAddons: []
    upgradeAddons: false
    keepAddons: true
    image:
      pullPolicy: IfNotPresent

