apiVersion: apps.kubeblocks.io/v1alpha1
kind: Cluster
metadata:
  name: blog-db
  namespace: lessons-in-progress
spec:
  clusterDefinitionRef: mysql
  clusterVersionRef: mysql-8.0.30
  terminationPolicy: Delete
  topology:
    mode: Standalone
    replicas: 1
  storage:
    dataVolumeClaimSpec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi
