apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:t69UIGw=,iv:D5hJc+RVBh7+vpmt2LgGks5CRM+WKDkhOd2SdNDycpk=,tag:Z4H2AIPYxcuTF/2NKde54w==,type:str]
    admin-password: ENC[AES256_GCM,data:x5ClcUCQ4qtV+QeRdj6tq1dtVLM=,iv:jx7AhdATode2RdLbMzby4KjQqsPiPGX/XLUfNijtzVg=,tag:uZTWHQq907hsTVL8vFs6Eg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tknk79czu7utxqpkampa72mxdmh0atwfjsqeda9egwu2xfvn8qaqr43j44
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1VjNXTW0zUjUxOUNaTGNq
            VHpzeWUxdG1hNzkrbHZ2YWVwMTZ1cERZMFFJCkgvREppcGF0dGYrd0FSUGJBMUMr
            Q1ZiT010UVJUZ3hFWWxNMlBWemd1Qm8KLS0tIHFpaTMxUlRoUlZEYWFJSTNBTHRx
            L3I5ajZyOUhYZEJpSXZNRzloOGdVNEEKfVGxb3k/ffypkT8iHUh7Vl4Qigqlz9Do
            ckPdqnRZwjjupEP5W4SiK6aInQwfn3Mm0m1YvGBWXQBEiRs+1I7hbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-27T14:16:00Z"
    mac: ENC[AES256_GCM,data:akEjB0shz9GtynseziOskx8mBUrTpYo71wH6nzpSNfRGHTKDBvxaCTHzuPj/EKMh4hGOO1EvKvwZX/smuL7sVb3cI3Rs8hT0TF2iBXmSgmfGmdCAh5XU3UzmAqihKjGUefVjJ+tqCSLAEYNZgQ7TlkFsxc6QuJxJPdXye7WjmVY=,iv:UlkQa3f5mlAh63i3E6eg7fdCwgzIdIiPKOX5haRyUfA=,tag:KtwMrizkEk+iMiw/jZqtEw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
